name: Build Python Wheels

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Unit test on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version:
          - 37
          - 38
          - 39
          - 310
          - 311
          - 312
          - 313
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build wheels
        env:
          TOXENV: "py${{ matrix.python-version }}"
        run: make test

  package:
    name: Publish wheels
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version:
          - 37
          - 38
          - 39
          - 310
          - 311
          - 312
          - 313
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build wheels
        env:
          CIBW_BUILD: "cp${{ matrix.python-version }}-*"
        run: uvx cibuildwheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
          print-hash: true
