name: Build Python Wheels

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  package:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    # environment: PyPI
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version:
          - cp36
          - cp39
          - cp311
          - cp312
          - cp313
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build wheels
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
        run: uvx cibuildwheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          packages-dir: wheelhouse
          print-hash: true
