name: Build Python Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    strategy:
      matrix:
        python-version:
          - cp36
          - cp39
          - cp311
          - cp312
          - cp313
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
