name: Build Python Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - cp36
          - cp39
          - cp311
          - cp312
          - cp313
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build wheels
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
        run: uvx cibuildwheel --output-dir wheelhouse

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.python-version }}"
          path: wheelhouse/*.whl
